apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myharset
  labels:
    app: myharset
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: hapod
  template:
    metadata:
      labels:
        app: hapod
        role: standby
    spec:
      containers:
      - name: myhapod
        image: mygoudpsrv:v1
        stdin: true
        tty: true
        command: [ "/usr/bin/goudps" ]
        resources:
          requests:
            ephemeral-storage: "1Gi"
          limits:
            ephemeral-storage: "2Gi"
      restartPolicy: Always
